pinterest_clone/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
    member do
      patch 'vote_for'
    end
  end

  root to: "pins#index"
end

pinterest_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

pinterest_clone/app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  acts_as_votable
end

pinterest_clone/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins, dependent: :destroy
end

pinterest_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

pinterest_clone/app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy, :vote_for]
  before_action :authenticate_user!, except: [:index, :show, :vote_for]
  before_action :authorized_user?, only: [:edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def vote_for
    @pin.liked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: pins_url }
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pin
    @pin = Pin.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end

  def authorized_user?
    @pin = current_user.pins.find_by(id: params[:id])
    return unless @pin.blank?
    redirect_back fallback_location: pins_url,
                  notice: 'Not authorized user!'
  end
end

pinterest_clone/app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    hash = HashWithIndifferentAccess.new(
      success: 'alert-success',
      error:   'alert-danger',
      alert:   'alert-warning',
      notice:  'alert-info'
    )
    hash[flash_type] || flash_type.to_s
  end
end

pinterest_clone/app/helpers/pins_helper.rb
module PinsHelper
end

pinterest_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PinterestClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="container" id="main_content">
      <%= render 'shared/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

pinterest_clone/app/views/pins/_form.html.erb
<%= form_for pin, html: { multipart: true } do |f| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.file_field :image, class: 'form-control-file' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

pinterest_clone/app/views/pins/edit.html.erb
<div class="col-md-8 offset-md-2">
  <h1>Editing Pin</h1>

  <%= render 'form', pin: @pin %>

  <%= link_to 'Show', @pin %> |
  <%= link_to 'Back', pins_path %>
</div>

pinterest_clone/app/views/pins/index.html.erb
<div class="transitions-enabled infinite-scroll clearfix" id="pins">
  <% @pins.each do |pin| %>
  <div class="card box">
    <%= link_to pin do %>
      <%= image_tag pin.image.url, class: "card-image-top" %>
    <% end %>
    <div class="card-block">
      <h4 class="card-title"><%= link_to pin.title, pin %></h4>
    </div>
    <div class="card-footer">
      <small class="text-muted">Submitted by <%= pin.user.email %></small>
    </div>
  </div>
  <% end %>
</div>

pinterest_clone/app/views/pins/new.html.erb
<div class="col-md-8 offset-md-2">
  <h1>New Pin</h1>

  <%= render 'form', pin: @pin %>

  <%= link_to 'Back', pins_path, class: 'btn btn-secondary' %>
</div>

pinterest_clone/app/views/pins/show.html.erb
<div class="row" id="pin_show">
  <div class="col-md-8 offset-md-2">
    <div class="card-group">
      <div class="card">
        <div id="pin_image">
          <%= image_tag @pin.image.url(:medium), class: "card-image-top" %>
        </div>
        <div class="card-block">
          <h4 class="card-title"><%= @pin.title %></h4>
          <%= @pin.description %>
        </div>
        <div class="card-footer">
          <small class="text-muted">Submitted by <%= @pin.user.email %></small>
          <div class="btn-group float-right">
            <%= link_to vote_for_pin_path(@pin), method: :patch, remote: true, class: 'btn btn-secondary' do %>
            <%=   fa_icon 'heart' %>
            <span id="total_votes"><%= @pin.votes_for.size %></span>
            <% end %>
            <%= link_to 'Edit', edit_pin_path(@pin), class: 'btn btn-secondary' %>
            <%= link_to 'Destroy', pin_path(@pin), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-secondary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

pinterest_clone/app/views/pins/vote_for.js.erb
$("#total_votes").html("<%= @pin.votes_for.size %>")

pinterest_clone/app/views/shared/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'Puppy Reviews', root_path, class: "navbar-brand" %>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'New Pin', new_pin_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Account', edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
  </div>
</nav>

pinterest_clone/app/views/shared/_messages.html.erb
<% flash.each do |flash_type, flash_message| %>
  <div class="alert <%= bootstrap_class_for(flash_type) %> alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= flash_message %>
  </div>
<% end %>